### ISSUE TITLE
MLPClassifier Transformation error

### ISSUE THREAD

**Issue by flashwwf** [unixpickle/sk2torch#1]
Hi, I am having the following problem with the transformation of the MLPClassifier model using your tool. I am unable to solve this problem by debugging, so I would like to ask if it is a problem with the training of my sk-MLPClassifier model.  thanks

def Build_Models(X_dim):
    lay1 = X_dim
    lay2 = int(lay1*1.4)
    lay3 = int(lay2*0.3)
    models_list = MLPClassifier(hidden_layer_sizes=(lay1,lay2,lay3), learning_rate_init=0.01, max_iter=10000 ,activation='tanh', solver='sgd')
    return models_list

model= Build_Suspect_Models(108)
model.fit(X,y)
torch_model = sk2torch.wrap(model)

error：---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1071880/2847112742.py in <module>
----> 1 torch_model = sk2torch.wrap(model)
      2 torch.jit.script(model).save("/model.pt")

~/anaconda3/envs/mefa/lib/python3.7/site-packages/sk2torch/wrap.py in wrap(obj)
     60         for cls in x.supported_classes():
     61             if isinstance(obj, cls):
---> 62                 return x.wrap(obj)
     63     raise ValueError(f"unsupported sklearn estimator type: {type(obj)}")
     64 

~/anaconda3/envs/mefa/lib/python3.7/site-packages/sk2torch/nn.py in wrap(cls, obj)
     69     def wrap(cls, obj: MLPClassifier) -> "TorchMLPClassifier":
     70         return cls(
---> 71             module=_WrappedMLP.wrap(obj),
     72             label_binarizer=TorchLabelBinarizer.wrap(obj._label_binarizer),
     73         )

~/anaconda3/envs/mefa/lib/python3.7/site-packages/sk2torch/nn.py in wrap(cls, obj)
     32             w = torch.from_numpy(weights)
     33             b = torch.from_numpy(biases)
---> 34             module = nn.Linear(weights.shape[0], weights.shape[1], dtype=w.dtype)
     35             with torch.no_grad():
     36                 module.weight.copy_(w.t())

TypeError: __init__() got an unexpected keyword argument 'dtype'

**Comment by unixpickle** [comment]
That error makes me think your pytorch is very old and out of date. What version are you using?

**Comment by flashwwf** [comment]
Thank you very much. I tried to update the pytorch from 1.8 to 1.11 and solve this error successfully.
